# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 701a5439beb0558a7f32f9cc3068d29549b2c2c24bec805609ee70d672391201dc360bfbda4062ab305457fbf34579f6f803a7e3da31ce27b8ab2eb9146f1ce0

test:
  secret_key_base: 1642d4d57534f6860cb4893be1b7bc2783f0ee54ec9fd81a54055b58624cd35791fef480f98b94ebd9041cfb17fdc6ad8f7967e8ae2e21f5969149584ee9fa79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
